# markplus-plugin-render-catalog
## Catelog(Tabel of Content) support for [markplus](https://github.com/zhengxiaoyao0716/markplus).

***
## Setup
``` bash
npm i --save-dev markplus markplus-plugin-render-catalog
```

***
## Usage
### Simple:
``` json
{ "plugin": [ "render-catalog" ] }
```

### Default folded catalog:
``` json
{
    "plugin": [
        ["render-catalog", true]
    ]
}
```
